debug: true
repositoryUrl: https://github.com/Kinle/semantic-release-protected-branch-demo
branches:
  - name: main
  - name: ci/semantic-release
success: []
fail: []
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - "@semantic-release/github"
  - - "@semantic-release/exec"
    - prepareCmd: "sed -i 's/^version.*/version = ${nextRelease.version}/g' gradle.properties"
  - - "@semantic-release/git"
    - assets:
        - package.json
        - CHANGELOG.md
